### ISSUE TITLE
REVIT 2022

### ISSUE THREAD

**Issue by sechanbask** [bimone/addins-excelexporterimporter#2]
how to allow installation on REVIT 2022 ?

**Comment by Darkkrynn** [comment]
Hi

I can install for Revit 2022.

I have modified this files


![2021-11-23_23h38_44](https://user-images.githubusercontent.com/39972350/143141091-26ddb89d-f170-4e23-86b0-de5bd2633122.png)
Modify this file

![2021-11-23_23h40_27](https://user-images.githubusercontent.com/39972350/143141098-74413ed0-5c3c-419d-bd3f-560834006cfb.png)
PackageContents.xml

![2021-11-23_23h39_18](https://user-images.githubusercontent.com/39972350/143141095-ee2ce5b9-b091-49f8-9606-a9e5acc7de6a.png)
inside "Contents", copy folder 2021 to folder 2022


But i dont say how i can modify source code.


nice day

**Comment by gvangorp** [comment]
So far I see in the code, the installer has not been added to the solution. @vinnividivicci are you able to share the installer config files?

**Comment by joseph-kirkpatrick** [comment]
@Darkkrynn this works for R22 no problem, however for R23 not so much. It'll show up but when you try to export anything it just hangs. I emailed the devs and it looks like they've retired it and have made it available for the community to proceed.

**Comment by sechanbask** [comment]
I have change bimone by diroots sheetlink
